version: '3.8'

services:
  # --- CONTENEDOR 1: BASE DE DATOS MYSQL ---
  the-elder-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: the_elder_shop
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3307:3306"
    volumes:
      - elder_db_data:/var/lib/mysql
      - ./init-db/script.sql:/docker-entrypoint-initdb.d/1.sql
   
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345"]
      timeout: 20s
      retries: 5
      interval: 5s

  # --- CONTENEDOR 2: BACKEND API (FastAPI) ---
  the-elder-backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app 
    depends_on:
      the-elder-db:
        condition: service_healthy # 🔒 El backend se queda esperando hasta que el healthcheck de arriba dé OK

  # --- CONTENEDOR 3: FRONTEND (React + Vite) ---
  the-elder-frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - the-elder-backend # ⚡ Simplificado: arranca en cuanto el proceso del backend inicia

volumes:
  elder_db_data: