"""agregado de biblioteca cloudinary, route y servicio para subir imagenes

Revision ID: 0dd55adc6d37
Revises: c9b6aa9bc79a
Create Date: 2026-04-21 15:23:24.312408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd55adc6d37'
down_revision: Union[str, Sequence[str], None] = 'c9b6aa9bc79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('productos', sa.Column('image_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'image_public_id')
    op.drop_column('productos', 'image_url')
    # ### end Alembic commands ###
