"""agregado modelo detalle carrito

Revision ID: 29d70fd518c2
Revises: 71008edd7ff9
Create Date: 2026-04-07 18:12:01.812112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29d70fd518c2'
down_revision: Union[str, Sequence[str], None] = '71008edd7ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', 'reembolsado', name='estadopagoenum'), nullable=True),
    sa.Column('metodo', sa.Enum('tarjeta', 'mercadopago', 'transferencia', name='metodopagoenum'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('detalles_orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_orden_id'), 'detalles_orden', ['id'], unique=False)
    op.drop_table('orden_items')
    op.add_column('ordenes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ordenes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ordenes', 'metodo_pago',
               existing_type=mysql.ENUM('tarjeta', 'mercadopago'),
               nullable=True)
    op.alter_column('ordenes', 'estado',
               existing_type=mysql.ENUM('pendiente', 'pagado', 'cancelado'),
               type_=sa.Enum('pendiente', 'pagada', 'cancelada', name='estadoordenenum'),
               existing_nullable=True)
    op.add_column('usuarios', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'token_expiration')
    op.drop_column('usuarios', 'reset_password_token')
    op.drop_column('usuarios', 'email_verification_token')
    op.alter_column('ordenes', 'estado',
               existing_type=sa.Enum('pendiente', 'pagada', 'cancelada', name='estadoordenenum'),
               type_=mysql.ENUM('pendiente', 'pagado', 'cancelado'),
               existing_nullable=True)
    op.alter_column('ordenes', 'metodo_pago',
               existing_type=mysql.ENUM('tarjeta', 'mercadopago'),
               nullable=False)
    op.drop_column('ordenes', 'updated_at')
    op.drop_column('ordenes', 'created_at')
    op.create_table('orden_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orden_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('producto_variante_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], name=op.f('orden_items_ibfk_1')),
    sa.ForeignKeyConstraint(['producto_variante_id'], ['producto_variantes.id'], name=op.f('orden_items_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_detalles_orden_id'), table_name='detalles_orden')
    op.drop_table('detalles_orden')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    # ### end Alembic commands ###
