"""initial tables

Revision ID: 2e86ba04b774
Revises: 
Create Date: 2026-03-22 14:51:34.902950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e86ba04b774'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('productos_ibfk_2'), 'productos', type_='foreignkey')
    op.drop_column('productos', 'plataforma_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('plataforma_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('productos_ibfk_2'), 'productos', 'plataformas', ['plataforma_id'], ['id'])
    # ### end Alembic commands ###
