"""agregado enums para metodos de pago

Revision ID: 71008edd7ff9
Revises: f5aa09d102c3
Create Date: 2026-03-26 20:06:53.665461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71008edd7ff9'
down_revision: Union[str, Sequence[str], None] = 'f5aa09d102c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('total', sa.Float(), nullable=False))
    op.add_column('ordenes', sa.Column('metodo_pago', sa.Enum('tarjeta', 'mercadopago', name='metodopagoenum'), nullable=False))
    op.alter_column('ordenes', 'estado',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('pendiente', 'pagado', 'cancelado', name='estadoordenenum'),
               existing_nullable=True)
    op.create_index(op.f('ix_ordenes_id'), 'ordenes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordenes_id'), table_name='ordenes')
    op.alter_column('ordenes', 'estado',
               existing_type=sa.Enum('pendiente', 'pagado', 'cancelado', name='estadoordenenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('ordenes', 'metodo_pago')
    op.drop_column('ordenes', 'total')
    # ### end Alembic commands ###
