"""modificaciones a orden y detalle_orden

Revision ID: 76be67aae207
Revises: 29d70fd518c2
Create Date: 2026-04-16 14:46:13.377850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76be67aae207'
down_revision: Union[str, Sequence[str], None] = '29d70fd518c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_orden', sa.Column('producto_variante_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('detalles_orden_ibfk_2'), 'detalles_orden', type_='foreignkey')
    op.create_foreign_key(None, 'detalles_orden', 'producto_variantes', ['producto_variante_id'], ['id'])
    op.drop_column('detalles_orden', 'variante_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_orden', sa.Column('variante_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'detalles_orden', type_='foreignkey')
    op.create_foreign_key(op.f('detalles_orden_ibfk_2'), 'detalles_orden', 'producto_variantes', ['variante_id'], ['id'])
    op.drop_column('detalles_orden', 'producto_variante_id')
    # ### end Alembic commands ###
