"""modificacion de modelo producto limite definido para Strings

Revision ID: 8ad1ac98f7af
Revises: d96bc9e182ad
Create Date: 2026-03-26 12:58:34.644713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad1ac98f7af'
down_revision: Union[str, Sequence[str], None] = 'd96bc9e182ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
