"""tabla variantes_digitales

Revision ID: 96ade67d3856
Revises: 0dd55adc6d37
Create Date: 2026-05-15 20:03:15.122625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ade67d3856'
down_revision: Union[str, Sequence[str], None] = '0dd55adc6d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variantes_digitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('url_descarga', sa.String(length=500), nullable=False),
    sa.Column('peso_gb', sa.Float(), nullable=True),
    sa.Column('instrucciones_canje', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variante_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variantes_digitales')
    # ### end Alembic commands ###
