"""modificacion de modelos para permitir formato y variantes de producto

Revision ID: 978bb193b85a
Revises: a70434b3875f
Create Date: 2026-03-24 15:09:35.705184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '978bb193b85a'
down_revision: Union[str, Sequence[str], None] = 'a70434b3875f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('producto_variantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('plataforma_id', sa.Integer(), nullable=True),
    sa.Column('formato_id', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['formato_id'], ['formatos.id'], ),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataformas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videojuegos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('anio_lanzamiento', sa.Integer(), nullable=True),
    sa.Column('jugadores_max', sa.Integer(), nullable=True),
    sa.Column('es_cooperativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videojuegos_id'), 'videojuegos', ['id'], unique=False)
    op.create_table('videojuego_genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuegos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_producto_plataforma_id'), table_name='producto_plataforma')
    op.drop_table('producto_plataforma')
    op.alter_column('plataformas', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_plataformas_id'), table_name='plataformas')
    op.add_column('productos', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.add_column('productos', sa.Column('precio_base', sa.Float(), nullable=True))
    op.drop_column('productos', 'precio')
    op.alter_column('tipos_producto', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipos_producto', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.add_column('productos', sa.Column('precio', mysql.FLOAT(), nullable=False))
    op.drop_column('productos', 'precio_base')
    op.drop_column('productos', 'descripcion')
    op.create_index(op.f('ix_plataformas_id'), 'plataformas', ['id'], unique=False)
    op.alter_column('plataformas', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_table('producto_plataforma',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plataforma_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataformas.id'], name=op.f('producto_plataforma_ibfk_2')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('producto_plataforma_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_producto_plataforma_id'), 'producto_plataforma', ['id'], unique=False)
    op.drop_table('videojuego_genero')
    op.drop_index(op.f('ix_videojuegos_id'), table_name='videojuegos')
    op.drop_table('videojuegos')
    op.drop_table('producto_variantes')
    op.drop_table('generos')
    op.drop_table('formatos')
    # ### end Alembic commands ###
