"""modelos modificados para permitir stock en consolas

Revision ID: a70434b3875f
Revises: 631521995cec
Create Date: 2026-03-23 19:03:52.915621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a70434b3875f'
down_revision: Union[str, Sequence[str], None] = '631521995cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto_plataforma', sa.Column('stock', sa.Integer(), nullable=True))
    op.drop_column('productos', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('producto_plataforma', 'stock')
    # ### end Alembic commands ###
