"""modificacion de modelo usuario para agregar mas campos, agregado de schemas paa usuario y admin, modificado rutas aauth

Revision ID: c9b6aa9bc79a
Revises: 76be67aae207
Create Date: 2026-04-19 14:55:04.625412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9b6aa9bc79a'
down_revision: Union[str, Sequence[str], None] = '76be67aae207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('usuarios', sa.Column('rol', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False))
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('provincia', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('usuarios', 'nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuarios', 'apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.alter_column('usuarios', 'apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('usuarios', 'created_at')
    op.drop_column('usuarios', 'direccion')
    op.drop_column('usuarios', 'ciudad')
    op.drop_column('usuarios', 'provincia')
    op.drop_column('usuarios', 'telefono')
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###
